# Install script for directory: /home/robin/NTRTsim/OpenSceneGraph/src/osg

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "libopenscenegraph")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES
    "/home/robin/NTRTsim/OpenSceneGraph/src/osg/CMakeFiles/CMakeRelink.dir/libosg.so.3.6.4"
    "/home/robin/NTRTsim/OpenSceneGraph/src/osg/CMakeFiles/CMakeRelink.dir/libosg.so.160"
    "/home/robin/NTRTsim/OpenSceneGraph/src/osg/CMakeFiles/CMakeRelink.dir/libosg.so"
    )
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "libopenscenegraph-dev")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/osg" TYPE FILE FILES
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/io_utils"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/os_utils"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/AlphaFunc"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/AnimationPath"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ApplicationUsage"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ArgumentParser"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Array"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/AttributeDispatchers"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/AudioStream"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/AutoTransform"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Billboard"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BindImageTexture"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BlendColor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BlendEquation"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BlendEquationi"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BlendFunc"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BlendFunci"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BoundingBox"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BoundingSphere"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BoundsChecking"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/buffered_value"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BufferIndexBinding"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BufferObject"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/BufferTemplate"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Callback"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Camera"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CameraView"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Capability"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ClampColor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ClearNode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ClipControl"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ClipNode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ClipPlane"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ClusterCullingCallback"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CollectOccludersVisitor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ColorMask"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ColorMaski"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ColorMatrix"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ComputeBoundsVisitor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/DispatchCompute"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ContextData"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ConvexPlanarOccluder"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ConvexPlanarPolygon"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CoordinateSystemNode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CopyOp"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CullFace"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CullingSet"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CullSettings"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/CullStack"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/DeleteHandler"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Depth"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/DepthRangeIndexed"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/DisplaySettings"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Drawable"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/DrawPixels"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Endian"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Export"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/fast_back_stack"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Fog"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/FragmentProgram"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/FrameBufferObject"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/FrameStamp"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/FrontFace"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Geode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Geometry"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GL2Extensions"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GLDefines"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GLExtensions"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GLObjects"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GLU"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GraphicsCostEstimator"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GraphicsContext"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GraphicsThread"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Group"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Hint"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Identifier"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Image"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ImageSequence"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ImageStream"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ImageUtils"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/KdTree"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Light"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/LightModel"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/LightSource"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/LineSegment"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/LineStipple"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/LineWidth"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/LOD"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/LogicOp"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Material"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Math"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Matrix"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Matrixd"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Matrixf"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/MatrixTransform"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/MixinVector"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Multisample"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Node"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/NodeCallback"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/NodeTrackerCallback"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/NodeVisitor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Notify"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Object"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/observer_ptr"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Observer"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ObserverNodePath"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/OccluderNode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/OcclusionQueryNode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/OperationThread"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PatchParameter"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PagedLOD"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Plane"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Point"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PointSprite"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PolygonMode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PolygonOffset"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PolygonStipple"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Polytope"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PositionAttitudeTransform"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PrimitiveSet"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PrimitiveSetIndirect"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/PrimitiveRestartIndex"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Program"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Projection"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ProxyNode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Quat"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Referenced"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ref_ptr"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/RenderInfo"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/SampleMaski"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Sampler"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Scissor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ScissorIndexed"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ScriptEngine"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Sequence"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ShadeModel"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Shader"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ShaderAttribute"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ShaderComposer"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ShadowVolumeOccluder"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Shape"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ShapeDrawable"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/State"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/StateAttribute"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/StateAttributeCallback"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/StateSet"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Stats"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Stencil"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/StencilTwoSided"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Switch"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TemplatePrimitiveFunctor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TemplatePrimitiveIndexFunctor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TexEnv"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TexEnvCombine"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TexEnvFilter"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TexGen"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TexGenNode"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TexMat"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Texture"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Texture1D"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Texture2D"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Texture2DMultisample"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Texture2DArray"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Texture3D"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TextureBuffer"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TextureCubeMap"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TextureRectangle"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Timer"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TransferFunction"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Transform"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TriangleFunctor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TriangleIndexFunctor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/TriangleLinePointIndexFunctor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Types"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Uniform"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/UserDataContainer"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ValueObject"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ValueMap"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ValueStack"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2b"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2d"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2f"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2i"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2s"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2ub"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2ui"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec2us"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3b"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3d"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3f"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3i"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3s"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3ub"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3ui"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec3us"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4b"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4d"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4f"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4i"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4s"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4ub"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4ui"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Vec4us"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/VertexAttribDivisor"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/VertexArrayState"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/VertexProgram"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/View"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Viewport"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/ViewportIndexed"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Version"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/Config"
    "/home/robin/NTRTsim/OpenSceneGraph/include/osg/GL"
    )
endif()

